# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: alpine:latest

pages:
  script:
  - echo 'Nothing to do...'

  artifacts:
    paths:
    - public
  only:
  - master
