name: NodeJS with Webpack

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm install
        npm build

    - name: Build
      run: |
        npm build

    - name: Lint
      run: |
        npm lint

    - name: Test unit
      run: |
        npm test:unit
        
    - name: Test e2e
      run: |
        npm test:e2e
